# Generated by Django 6.0.3 on 2026-03-12 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptnode',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptnode',
            name='easiness',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='conceptnode',
            name='engage_pref',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='conceptnode',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conceptnode',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conceptnode',
            name='mastery',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='conceptnode',
            name='struggling',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LearnerEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('mastered', 'Mastered'), ('struggling-with', 'Struggling With'), ('has-read', 'Has Read'), ('requires-prereq', 'Requires Prerequisite'), ('encountered-tutor', 'Encountered in Tutor')], max_length=30)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='core.conceptnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='core.conceptnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source', 'target', 'edge_type')},
            },
        ),
    ]
